import { CreditCardAccount } from "@/types/account";

export function getMockAccounts(): CreditCardAccount[] {
  const today = new Date();
  const dueDate = (daysFromNow: number) => {
    const d = new Date(today);
    d.setDate(d.getDate() + daysFromNow);
    return d.toISOString().split("T")[0];
  };
  const pastDate = (daysAgo: number) => {
    const d = new Date(today);
    d.setDate(d.getDate() - daysAgo);
    return d.toISOString().split("T")[0];
  };

  return [
    {
      id: "acc_cap1_venture_x",
      name: "Capital One Venture X",
      last4: "1795",
      institution: "Capital One",
      currentBalance: 3200.00,
      creditLimit: 20000,
      availableCredit: 16800.00,
      paymentDueDate: dueDate(10),
      minimumPayment: 96.00,
      apr: 0.2699,
      lastPaymentAmount: 400.00,
      lastPaymentDate: pastDate(15),
      color: "#d03027",
    },
    {
      id: "acc_cap1_savor",
      name: "Capital One Savor",
      last4: "9365",
      institution: "Capital One",
      currentBalance: 1850.00,
      creditLimit: 10000,
      availableCredit: 8150.00,
      paymentDueDate: dueDate(14),
      minimumPayment: 55.00,
      apr: 0.2499,
      lastPaymentAmount: 200.00,
      lastPaymentDate: pastDate(20),
      color: "#c5232a",
    },
    {
      id: "acc_cap1_quicksilver",
      name: "Capital One Quicksilver",
      last4: "9996",
      institution: "Capital One",
      currentBalance: 920.00,
      creditLimit: 5000,
      availableCredit: 4080.00,
      paymentDueDate: dueDate(18),
      minimumPayment: 28.00,
      apr: 0.2199,
      lastPaymentAmount: 150.00,
      lastPaymentDate: pastDate(12),
      color: "#1a3c6e",
    },
    {
      id: "acc_citi_double_cash",
      name: "Citi Double Cash Card",
      last4: "9538",
      institution: "Citibank",
      currentBalance: 4100.00,
      creditLimit: 15000,
      availableCredit: 10900.00,
      paymentDueDate: dueDate(7),
      minimumPayment: 123.00,
      apr: 0.1899,
      lastPaymentAmount: 350.00,
      lastPaymentDate: pastDate(18),
      color: "#003b70",
    },
    {
      id: "acc_amex_bcp",
      name: "Amex Blue Cash Preferred",
      last4: "2004",
      institution: "American Express",
      currentBalance: 2650.00,
      creditLimit: 12000,
      availableCredit: 9350.00,
      paymentDueDate: dueDate(5),
      minimumPayment: 79.00,
      apr: 0.2199,
      lastPaymentAmount: 250.00,
      lastPaymentDate: pastDate(25),
      color: "#006fcf",
    },
    {
      id: "acc_amex_bce",
      name: "Amex Blue Cash Everyday",
      last4: "2005",
      institution: "American Express",
      currentBalance: 1380.00,
      creditLimit: 8000,
      availableCredit: 6620.00,
      paymentDueDate: dueDate(5),
      minimumPayment: 41.00,
      apr: 0.2049,
      lastPaymentAmount: 175.00,
      lastPaymentDate: pastDate(25),
      color: "#c5a44e",
    },
    {
      id: "acc_chase_ur",
      name: "Chase Ultimate Rewards",
      last4: "1392",
      institution: "Chase",
      currentBalance: 1950.00,
      creditLimit: 10000,
      availableCredit: 8050.00,
      paymentDueDate: dueDate(12),
      minimumPayment: 58.00,
      apr: 0.2399,
      lastPaymentAmount: 300.00,
      lastPaymentDate: pastDate(16),
      color: "#1a5276",
    },
    {
      id: "acc_robinhood",
      name: "Robinhood Credit Card",
      last4: "1922",
      institution: "Robinhood",
      currentBalance: 580.00,
      creditLimit: 3000,
      availableCredit: 2420.00,
      paymentDueDate: dueDate(20),
      minimumPayment: 25.00,
      apr: 0.1699,
      lastPaymentAmount: 100.00,
      lastPaymentDate: pastDate(8),
      color: "#00c805",
    },
    {
      id: "acc_apple_card",
      name: "Apple Card",
      last4: "••••",
      institution: "Apple / Goldman Sachs",
      currentBalance: 740.00,
      creditLimit: 6000,
      availableCredit: 5260.00,
      paymentDueDate: dueDate(28),
      minimumPayment: 25.00,
      apr: 0.2449,
      lastPaymentAmount: 200.00,
      lastPaymentDate: pastDate(5),
      color: "#555555",
    },
  ];
}
